### ISSUE TITLE
Just a thanks

### ISSUE THREAD

**Issue by shaps80** [nonameplum/UIEnvironment#1]
Hey there, I've been working exclusively with SwiftUI for a while now and I've recently had to revisit UIKit for a project.

I was missing this kind of propagation and I love that you've come up with a really well implemented and elegant solution, let alone API-matching.

I really appreciate the effort you put it so thank you!

Just curious, 9 months later, have you found any issues with your approach that I might need to be aware of?

**Comment by nonameplum** [comment]
Hey,

To be honest for me it was a pet project, not really tested in a production app.

But I guess the whole concept works quite well, in some cases maybe it might be adjusted to your needs.
Feel free to make an issue if you would find some missing features or behaviours.

I tried to make couple of unit tests that prove the current behaviours to work.

For my demo, pet app I verified few uses cases it worked quite nice.

**Comment by shaps80** [comment]
Fair enough, nice work though 👍

**Comment by lgvv** [comment]
awesome, thanks too.

I was hoping to apply TCA's Dependency in UIKit as well. 
The simple implementation through EnvironmentKey and EnvironmentValue didn't work as expected.
I came across your article on Medium and X(Twitter), and it caught my attention!

I am also looking to implement the project in UIKit, and I'm curious about its stability.

Wishing it becomes something as innovative as ReactiveX.
