### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by john-07** [nonameplum/UIEnvironment#2]
I got a crash when calling the "setupOverrideUserInterfaceListener" function. I would like to be able to disable all these additional listeners. Also, in the "traverseTopDown" function, I would like to add the "isViewLoaded" check before accessing the "ViewController.view.traverse"

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIInputSetContainerView swizzled_setOverrideUserInterfaceStyle:]: unrecognized selector sent to instance 0x15b728110'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109749138 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00000001083ffdb4 objc_exception_throw + 56
	2   CoreFoundation                      0x000000010975df88 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   UIKitCore                           0x00000001291a24e4 -[UIResponder doesNotRecognizeSelector:] + 232
	4   CoreFoundation                      0x000000010974d288 ___forwarding___ + 1280
	5   CoreFoundation                      0x000000010974f5ac _CF_forwarding_prep_0 + 92
	6   Boardmaps                           0x00000001042d5f8c $sSo8UIWindowC13UIEnvironmentE38swizzled_setOverrideUserInterfaceStyle33_0DDEEE99711FE8829632050334144882LLyySo06UIUsergH0VF + 56
	7   Boardmaps                           0x00000001042d601c $sSo8UIWindowC13UIEnvironmentE38swizzled_setOverrideUserInterfaceStyle33_0DDEEE99711FE8829632050334144882LLyySo06UIUsergH0VFTo + 52
	8   UIKitCore                           0x0000000128f24df8 -[UIInputSetContainerView _setRenderConfig:] + 168
	9   UIKitCore                           0x0000000128f24cd0 -[UIInputSetContainerView initWithFrame:] + 136
	10  UIKitCore                           0x0000000128f2692c -[UIInputWindowController loadView] + 52
	11  UIKitCore                           0x0000000128a3fad4 -[UIViewController loadViewIfRequired] + 152
	12  UIKitCore                           0x0000000128a40070 -[UIViewController view] + 20
	13  UIKitCore                           0x00000001291acc4c -[UIWindow addRootViewControllerViewIfPossible] + 380
	14  UIKitCore                           0x00000001291adbe4 -[UIWindow setRootViewController:] + 360
	15  UIKitCore                           0x0000000129487664 -[UITextEffectsWindow _commonInitWithOptions:] + 248
	16  UIKitCore                           0x0000000129487338 -[UITextEffectsWindow(UIObjectsForPerCanvas) _initWithCanvas:options:] + 204
	17  UIKitCore                           0x000000012955276c +[_UIObjectPerCanvas objectOfClass:forCanvas:withOptions:createIfNecessary:] + 632
	18  UIKitCore                           0x0000000129488ec0 +[UITextEffectsWindow _sharedTextEffectsWindowforWindowScene:allowHosted:forViewService:matchesStatusBarOrientationOnAccess:shouldCreateIfNecessary:] + 604
	19  UIKitCore                           0x000000012948902c +[UITextEffectsWindow sharedTextEffectsWindowForWindowScene:forViewService:] + 208
	20  UIKitCore                           0x0000000128b921d0 -[UIKeyboardSceneDelegate containerWindowForViewService:] + 328
	21  UIKitCore                           0x0000000128b9228c -[UIKeyboardSceneDelegate containerRootController] + 16
	22  UIKitCore                           0x0000000128b99b54 -[UIKeyboardSceneDelegate refreshKeyboardLayoutGuide] + 16
	23  UIKitCore                           0x00000001291a82e4 -[UIWindow addKeyboardLayoutGuideIfNeeded:] + 204
	24  UIKitCore                           0x00000001296733f4 -[UIView _constrainKeyboardGuideToWindowGuideIfNeeded:] + 52
	25  UIKitCore                           0x0000000129691f00 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1260
	26  UIKitCore                           0x0000000129691cbc -[UIView(Internal) _didMoveFromWindow:toWindow:] + 680
	27  UIKitCore                           0x0000000129691cbc -[UIView(Internal) _didMoveFromWindow:toWindow:] + 680
	28  UIKitCore                           0x0000000129691cbc -[UIView(Internal) _didMoveFromWindow:toWindow:] + 680
	29  UIKitCore                           0x0000000129691cbc -[UIView(Internal) _didMoveFromWindow:toWindow:] + 680
	30  UIKitCore                           0x0000000129691cbc -[UIView(Internal) _didMoveFromWindow:toWindow:] + 680
	31  UIKitCore                           0x000000012968754c __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 120
	32  CoreAutoLayout                      0x00000001118925e0 -[NSISEngine withBehaviors:performModifications:] + 76
	33  UIKitCore                           0x0000000129687478 -[UIView _postMovedFromSuperview:] + 448
	34  UIKitCore                           0x000000012969416c -[UIView(Internal) _addSubview:positioned:relativeTo:] + 2212
	35  UIKitCore                           0x000000012965f990 -[UITransitionView transition:fromView:toView:removeFromView:] + 864
	36  UIKitCore                           0x0000000128a5e464 -[UIViewControllerBuiltinTransitionViewAnimator animateTransition:] + 1192
	37  UIKitCore                           0x0000000128a64a58 ___UIViewControllerTransitioningRunCustomTransition_block_invoke_3 + 48
	38  UIKitCore                           0x0000000128b9b7a4 +[UIKeyboardSceneDelegate _pinInputViewsForKeyboardSceneDelegate:onBehalfOfResponder:duringBlock:] + 88
	39  UIKitCore                           0x0000000128a649f0 ___UIViewControllerTransitioningRunCustomTransition_block_invoke_2 + 168
	40  UIKitCore                           0x000000012968dfac +[UIView(Animation) _setAlongsideAnimations:toRunByEndOfBlock:] + 148
	41  UIKitCore                           0x0000000128a64890 _UIViewControllerTransitioningRunCustomTransition + 432
	42  UIKitCore                           0x00000001289594b8 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke_3 + 1540
	43  UIKitCore                           0x000000012963de48 -[_UIAfterCACommitBlock run] + 64
	44  UIKitCore                           0x000000012963e258 -[_UIAfterCACommitQueue flush] + 160
	45  libdispatch.dylib                   0x000000010d9bfec4 _dispatch_call_block_and_release + 24
	46  libdispatch.dylib                   0x000000010d9c173c _dispatch_client_callout + 16
	47  libdispatch.dylib                   0x000000010d9d13f8 _dispatch_main_queue_drain + 1228
	48  libdispatch.dylib                   0x000000010d9d0f1c _dispatch_main_queue_callback_4CF + 40
	49  CoreFoundation                      0x00000001096a99a0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
	50  CoreFoundation                      0x00000001096a40b8 __CFRunLoopRun + 1936
	51  CoreFoundation                      0x00000001096a3514 CFRunLoopRunSpecific + 572
	52  GraphicsServices                    0x0000000111463ae4 GSEventRunModal + 160
	53  UIKitCore                           0x0000000129177040 -[UIApplication _run] + 868
	54  UIKitCore                           0x000000012917acc8 UIApplicationMain + 124
	55  Boardmaps                           0x0000000103556d6c main + 180
	56  dyld                                0x0000000106051544 start_sim + 20
	57  ???                                 0x00000001062620e0 0x0 + 4398129376
	58  ???                                 0x366e800000000000 0x0 + 3922213062974636032
)
libc++abi: terminating due to uncaught exception of type NSException

**Comment by nonameplum** [comment]
Please try out the new release [1.1.0](https://github.com/nonameplum/UIEnvironment/releases/tag/1.1.0) that besides fixing the crash on iOS 17.x. Also, it allows to configure the default listeners/hooks https://github.com/nonameplum/UIEnvironment/blob/e221cbe57bcc099a349fd406ec1073985ce5f2aa/Sources/UIEnvironment/UIEnvironmentValues%2BPredefinedListeners.swift#L10

**Comment by john-07** [comment]
Thank you. You write very interestingly and I have learned very useful things from you
